### ISSUE TITLE
How to use travis_wait with arch-travis?

### ISSUE THREAD

**Issue by vonpupp** [mikkeloscar/arch-travis#20]
Hello,

I am running a build that takes a while and for more than 10min it doesn't get any console output and therefore travis terminates that build and assumes an error. I have searched on how to fix this and I found the `travis_wait` command, however when I try to use it with arch-travis I get an error (code 6 error).

Any ideas?

Herewith the [build log] when I use `travis_wait`, and this is my `.travis.yml` file.

Thank you very much.

```yaml
env:
  global:
    - ARCH_TRAVIS_CLEAN_CHROOT=1
  matrix:
      # Upgrade
    - TAGS="-t upgrade"
      # Packages
    - TAGS="-t packages_cui_minimal"
    - TAGS="-t packages_cui_workstation"
    - TAGS="-t packages_gui_xorg"
    - TAGS="-t packages_gui_awesome_wm"
    - TAGS="-t packages_gui_fonts"
    - TAGS="-t packages_gui_apps"
      # Writing suite
    - TAGS="-t packages_suite_latex"
    - TAGS="-t packages_suite_libreoffice"
      # AUR
    - TAGS="-t yaourt"
    - TAGS="-t packages_cui_aur"                ENVARS='-e user=travis'
    - TAGS="-t packages_gui_aur"                ENVARS='-e user=travis'
      # Devel
    - TAGS="-t devel_env_python"                ENVARS='-e user=travis'
      # All
    - TAGS="-t all"                             ENVARS='-e user=travis'

language: python
sudo: required

arch:
  packages:
    - yaourt
  script:
    - ./bootstrap/archlinux/guest-archlinux-setup-dependencies.sh
    - sudo ./setup-root.sh
    - sudo ./setup-user.sh $TAGS $ENVARS -vvvv

script:
  - travis_wait 60 "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
```

[build log]: https://travis-ci.org/vonpupp/ansible-personal/builds/186814239

**Comment by mikkeloscar** [comment]
It won't work that way because you are using pipe in the command. But I would expect something like this to work:

```yaml
script:
  - travis_wait 60 sh -c "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
```

But that doesn't seem to work either.

Seems like a travis issue to me since it can't handle `sh -c` as the command passed to `travis_wait` which I would expect.

**Comment by vonpupp** [comment]
Thank you very much @mikkeloscar for pointing me into the right direction, I didn't thought about the pipe. I solved it =)

**Comment by xeon-zolt** [comment]
@mikkeloscar  i am also having same problem please help me 
```

sudo: required

arch:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    # pacman packages
    - yaourt
    - archiso
  script:

    - ./build-repo
    - sudo ./build.sh -v

before_install:
- export -f travis_wait

script:
  - travis_wait 30 sh -c "curl -s https://raw.githubusercontent.com/xeon-zolt/arch-travis/master/arch-travis.sh | bash"
  
```

and logs https://travis-ci.org/xeon-zolt/Event-linux
