### ISSUE TITLE
expose '.ccache' and 'pacman cache' to travis caching facility.

### ISSUE THREAD

**Issue by bartoszek** [mikkeloscar/arch-travis#55]
Could we have `$TRAVIS_HOME/.ccache` and '/var/cache/pacman/pkg' mounted in the same maner as `build_dir` #7 ?
This will expose `.ccache` and `pacman cache` to travis caching infrastructure, those reducing build time :bulb: 

_I would like to abuse Travis-CI a bit, and bodge a build-bot for my AUR packages :smirk: [e.g.](https://github.com/bartoszek/AUR-repo)_

**Comment by bartoszek** [comment]
I've tried to add `docker volume` with `docker run -v $HOME/.ccache -v $HOME/.arch-cache:/var/cache/pacman/pkg` but got `permissin error` during`makepkg` in both deps sync and compilation.
https://travis-ci.org/bartoszek/AUR-oidn/builds/537564034

**Comment by bartoszek** [comment]
I menage to work around `Travis` ccache and make local one in the build path, without modifying `arch-travis.sh`. 
```yml
cache:
  directories:
  - .ccache

services:
- docker

arch:
  repos:
  - bartus=https://media.githubusercontent.com/media/bartoszek/AUR-repo/master
  packages:
  # arch/aur packages
  - ccache
  script:
  - "sed '/depends/a options=(ccache)' -i PKGBUILD"
  - "export CCACHE_DIR='/build/.ccache'"
  - "makepkg -s --noconfirm"
  - "ccache -s"
  
script:
#- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
- "mkdir .arch-cache||true"
- "curl -s https://raw.githubusercontent.com/bartoszek/arch-travis/pacman-pkg-cache/arch-travis.sh | bash"
- "CCACHE_DIR=\"$(pwd)/.ccache\" ccache -s"
```
But without including `/etc/makepkg.conf` in Docker image I can't get `yay` to use `ccache` too.
